ckpt_path: 
seed: 777
dataset: aiai
vid_dir: "/standard/spencerNSF/NeuralNetworksProjectVideos/314hours/Videos_314 Hours/"
annot_dir: "/standard/spencerNSF/NeuralNetworksProjectVideos/314hours/Video Annotations_314 Hours/"
prompt: '<CAPTION>' # '<MORE_DETAILED_CAPTION>'
output_dir: './ckpt_caption10'
batch_size: 16
workers: 16
label_defs: '/scratch/tkg5kq/sandbox/tmp/florence_experiments/aiai_dataloader/csv/label_definitions.csv'
loss:
    ce: 1
    info: 0
    i2t: 0
option: '1'
name: 'test_caption10_full'
size: 768
# Parameters
freeze_fc: True
lora: False
# Debugging and printing
debug: False
print: True
stunt: .1
freq: 2
threshold_method: sigmoid
eaf_mode: definition
# Learning rates and optimizers
solver:
    epochs: 50
    lr: 1.e-4
    mode: 'adamw'
    # # For SGD
    # # momentum: 0.9
    # # weight_decay: 0.2
    schedule: False
    type: 'cosine'
    lr_warmup_step: 5
    lr_decay_step: 15